# Site settings
baseurl = "http://improwised.gitlab.io/"
languageCode = "en-us"
title = "Improwised Technologies Pvt Ltd"
theme = "improwised_theme_stark"

# Enter your tracking code to enable Google Analytics
googleAnalytics = "UA-562351-11"
