# Site settings
baseurl = "https://www.improwised.com/"
languageCode = "en-us"
title = "Improwised Technologies Pvt Ltd"
theme = "improwised_theme_stark"

# Enter your tracking code to enable Google Analytics
googleAnalytics = "UA-562351-11"

[params]
  env = "production"
  API_URL = "https://rnnmftp4t7.execute-api.us-west-2.amazonaws.com/production/api/contactus"
  SITE_KEY = "6LfM73IUAAAAAFFFAv5jHjpT_UIjRZqD2xcijnwn"

disableKinds = ["taxonomy", "taxonomyTerm"]
